### ISSUE TITLE
Namespace vs Number space

### ISSUE THREAD

**Issue by smutt** [large-bgp-communities/large-bgp-communities#13]
I think the term 'number space' or possibly 'number-space' would be preferable to 'namespace' in this document. AS numbers and BGP communities are not names and thus don't belong in a namespace. Also, RFC 6793 uses the term 'number space' in its title.

**Comment by job** [comment]
Hi,

I appreciate the time you have taken for reviewing the document.

I believe that the term 'number space' has a different meaning in RFC 6793 then what is meant and needed in the large communities document.

A "namespace" is a a class of elements (e.g. addresses, file locations, numbers, etc.) in which each element has an identifier (name) unique to that class, although it may be shared with elements in other classes.

I have no idea why they used the word "Number Space" in rfc6793. The term doesn't even return anywhere in the text. I am rejecting this suggestion, most people will have an easier time understanding the meaning through a well known term such as "namespace".

If you do not agree with my rejection, please raise the comment on idr@ietf.org and we can assess what the working group thinks.

Kind regards,

Job
